---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zzk-front-secret
  namespace: zzk-front
spec:
  encryptedData:
    BACKEND_URL: AgBN9E+/EBXJN/aWhT6dDh3/6kz7bfSX1p0ix+MqwN3tXliw+8vA/JnEnvfYAEQdm+fBJyQVKVMBkc7sUJgwI4dxu4R4iNvd3owJi2ivs16HPgE4jTNp68awLQgNcR5It10KWXsSzuPIbKIBbobSGf5X6aWHdEHRMP+JQB6GTQFPi8F8bVpP9wgJVk5YctEmV67HYrlkutweIUMObs6Crgqw78GMRs6C05zeFk0IMAZLGYbTcJjRXZuFhGElE/EMdTPh+y3/uw1zndYkBxDwHVvwWMkFDFmHoYgBbf9/8y6TL2SrUuL5POfiiznf1bqd+NIJJebBevaLoHtlm5ksKjroEI+7eLi9+qoTPTpiqwOYYFscTl0f0osyBoReXK69b1YtKJHn+VeSSnJFQCb/nS0KQr7twf8cX5nSnzzG2mqNHz6cyN7utWVlJBdTvw/olau00YxhQpiPamGYqL//yoZVbudjyZfzYKdAe4NjFUQ3WnhxpEmWFWL2+UpbbiJjSJBpoPqI4SQt23L8AnhGu2EvVZSedSEWAK1fskwCHyOfBl+D7am5bNllAQKvkUmWfvfUYhNqzXOIAPyUQubciLMRZNgzj+C3WlSenZ2qAJe+yVDFqNy17+emFhmVsqj1UYYBe1n+t1Krlw2PMRWO9qQ4qs9hMcg0dDCVZSweiA+G2F2D/74r7MTGPeuhLqVJNy+WITbGv3+NXbdkiX1Xhnk6Rcv+oyvtJjF0EURoFkYk12BUycTl/2u0/iV4PsgQZJsfObcyGca+
  template:
    metadata:
      name: zzk-front-secret
      namespace: zzk-front
    type: Opaque
